export default [
    {
        authors: "OWP",
        description: "The National Weather Service (NWS) is introducing the new National Water Prediction Service (NWPS), transforming how water resources information and services are delivered, and providing a greatly improved user experience\nthrough enhanced displays.\n\nThe NWS has hosted river observations and forecast information on the Advanced Hydrologic Prediction Service (AHPS) web page since the late 1990s. AHPS provides near real-time river data and forecasts visualized through static maps and hydrographs, probabilistic information, static Flood Inundation Maps (FIMs) at select locations, and quantitative precipitation estimates that enable decision making. Building upon these core capabilities, dynamic\nand interactive hydrographs with a longer observation period, are now available via NWPS in addition to expanded mapping controls and content. NWPS includes new tools such as dynamic real-time flood inundation mapping (for an\ninitial 10% of the U.S. population and growing to nearly 100% by 2026), greatly expanding the amount of information for making critical neighborhood scale water decisions. NWPS delivers enhanced visualization capabilities and an Application Programming Interface (API) which enables user applications to more efficiently access water resources data by leveraging modern web services",
        docs_url: "",
        embed_url: "",
        page_url: "https://water.noaa.gov/",
        resource_id: "e48fa7b8ef554e8e973b81fbca266013",
        resource_type: "Resource",
        resource_url: "https://www.hydroshare.org/resource/e48fa7b8ef554e8e973b81fbca266013/",
        thumbnail_url: "https://ciroh-portal-static-data.s3.us-east-1.amazonaws.com/e789e659-41c1-4683-bc3a-f7e68d41719c.png",
        title: "National Water Prediction Service (NWPS) Website",
    },
    {
        authors: "Cuahsi",
        description: "HydroShare is the web-based hydrologic information system operated by the Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI). Acting as a cloud-hosted repository, it allows researchers, educators, and water-resources professionals to upload, curate, publish, and permanently archive heterogeneous hydrologic data sets and computational models in many flexible formats. Each resource receives a persistent Digital Object Identifier (DOI), making it immediately citable, shareable, and discoverable through standard scholarly search engines. Beyond storage, HydroShare fosters collaboration: project members can organise resources into collections, set fine-grained privacy controls, and work together in real time within a browser-based workspace that eliminates file-exchange hassles. Integrated web applications—ranging from Python notebooks to map-centric visualisation and model-running tools—let users analyse or re-run data directly where it lives, providing a gateway to cloud computing. The platform is continually enhanced by CUAHSI’s development team under National Science Foundation awards ACI-1148453, ACI-1148090, EAR-1338606, OAC-1664018, OAC-1664061, and OAC-1664119.",
        docs_url: "",
        embed_url: "",
        page_url: "https://www.hydroshare.org/",
        resource_id: "cef9cfb6785e4836b63471622f48ce29",
        resource_type: "Resource",
        resource_url: "https://www.hydroshare.org/resource/cef9cfb6785e4836b63471622f48ce29/",
        thumbnail_url: "https://ciroh-portal-static-data.s3.us-east-1.amazonaws.com/55f0dd78-a0be-4523-8a8d-5ec3523036d1.png",
        title: "HydroShare",
    },
    {
        authors: " Manjila Singh 🖊  Arpita Patel 🖊  Nia Minor",
        description: "NextGen In A Box (NGIAB) - Advanced Hydrologic Modeling Platform\nNextGen In A Box (NGIAB) is a cutting-edge, containerized hydrologic modeling framework that brings the power of NOAA's Next Generation Water Resources Modeling Framework to researchers and practitioners worldwide. This innovative platform simplifies the deployment and execution of complex water prediction models through a user-friendly, portable environment. NGIAB enables users to run sophisticated hydrologic simulations without extensive infrastructure setup, making advanced water modeling accessible to organizations of all sizes.\nKey features include modular architecture for customizable modeling workflows, seamless integration with various data sources, built-in visualization tools for result analysis, and support for both local and cloud-based deployments. The platform supports multiple modeling engines and frameworks, allowing users to select the most appropriate tools for their specific applications. Whether for flood forecasting, water resource management, or research applications, NGIAB provides a comprehensive solution for modern hydrologic modeling needs. The system's containerized approach ensures consistency, reproducibility, and scalability across different computing environments.",
        docs_url: "https://ngiab.ciroh.org/",
        embed_url: "",
        page_url: "https://ngiab.ciroh.org/",
        resource_id: "3bcdb3f7cefd48f4af74cd4c83a647f3",
        resource_type: "Resource",
        resource_url: "https://www.hydroshare.org/resource/3bcdb3f7cefd48f4af74cd4c83a647f3/",
        thumbnail_url: "https://ciroh-portal-static-data.s3.us-east-1.amazonaws.com/a551dc55-5f40-4217-aaf9-c4dff155d13e.jpg",
        title: "NGIAB Product Portfolio Website",
    },
    {
        authors: ' Corey Krewson',
        description: 'A powerful dashboard designed to visualize and analyze hydrological data using the National Water Model (NWM) services. At its core, the application integrates an interactive map, time series plots, and statistical summaries to provide comprehensive insights for water resource management.The map component allows users to visualize geographical data, including river reaches and gauge locations, providing a spatial context for hydrological phenomena. The time series feature displays water flow data for each reach and gauge over time, enabling trend analysis and prediction. Meanwhile, the stats section aggregates data from various NWM services, offering key metrics such as flow forecasts, streamflow, and runoff predictions.This application is ideal for professionals in hydrology, researchers, and decision-makers who need a unified tool to assess and predict water conditions based on real-time and historical data. The dashboard features a high-resolution, layered map interface powered by NWM data, enabling users to overlay critical hydrological features such as river networks, streamflow pathways, USGS gauge stations, and flood risk zones. Users can toggle between real-time data (e.g., current streamflow, precipitation anomalies) and forecast models (e.g., 7-day flood projections) while leveraging spatial query tools to isolate specific watersheds or regions. Customizable basemaps (topographic, satellite, or hydrographic) and clickable features provide instant access to metadata, such as reach identifiers, elevation profiles, and historical flood events. Integration with geospatial APIs allows for cross-referencing with external datasets, such as land use patterns or infrastructure vulnerabilities, enhancing situational awareness for disaster preparedness.',
        docs_url: '',
        embed_url: '',
        page_url: 'https://tethys.ciroh.org/apps/tethysdash/',
        resource_id: '16e3318a244c4817b5d7c22759346c95',
        resource_type: 'Resource',
        resource_url: 'https://www.hydroshare.org/resource/16e3318a244c4817b5d7c22759346c95/',
        thumbnail_url: 'https://ciroh-portal-static-data.s3.us-east-1.amazonaws.com/e7f50c88-adcb-48b8-8e99-c1f54d0b9960.png',
        title: 'TethysDash',
    },
    {
        authors: " Anthony Castronova",
        description: "The CUAHSI JupyterHub is a web application that allows HydroShare users to execute scientific code in the cloud. It's hosted on the Google Cloud Platform and is maintained by the CUAHSI Compute staff. While this application supports the execution of a variety of codes, it’s primarily designed to write, build, and run Jupyter Notebooks. A Jupyter notebook is thus an enhanced computational environment that combines rich text and code execution into a single script-like container. The CUAHSI JupyterHub combines this functionality with the HydroShare data repository to provide a rich computational environment for water scientists.\n\nThe CUAHSI Jupyterhub is a scalable computational environment hosting on the Google Cloud Platform that has been carefully designed to provide maximum interoperability with the HydroShare data repository. The CUAHSI JupyterHub is a web application that allows HydroShare users to run code and models in the CUAHSI Compute Cloud. This application offers free, limited, computational resources primarily aimed at education and reproducible science.",
        docs_url: "",
        embed_url: "",
        page_url: "https://jupyterhub.cuahsi.org",
        resource_id: "33c45575b95f45c4bf7335faab67ed36",
        resource_type: "App Connector",
        resource_url: "https://www.hydroshare.org/resource/33c45575b95f45c4bf7335faab67ed36/",
        thumbnail_url: "https://avatars0.githubusercontent.com/u/17927519?v=3&s=400",
        title: "CUAHSI JupyterHub",
    },
    {
        authors: " Arpita Patel 🖊  Benjamin Lee 🖊  Nia Minor 🖊  Manjila Singh 🖊  Anthony Castronova",
        description: "CIROH 2i2c JupyterHub - Production Server\n\nCIROH, in collaboration with 2i2c, offers a dedicated JupyterHub environment on Google Cloud specifically designed for hydrological researchers. 2i2c is a cloud service provider specializing in open-source infrastructure for research and development.\n\nCIROH 2i2c Production environment - https://ciroh.awi.2i2c.cloud/\n\nTo gain access to this environment please reach out to ciroh-it-admin@ua.edu\n\nMore details: https://docs.ciroh.org/docs/services/cloudservices/2i2c/\n\nThis research was supported by the Cooperative Institute for Research to Operations in Hydrology (CIROH) with funding under award NA22NWS4320003 from the NOAA Cooperative Institute Program. The statements, findings, conclusions, and recommendations are those of the author(s) and do not necessarily reflect the opinions of NOAA.",
        docs_url: "",
        embed_url: "",
        page_url: "",
        resource_id: "2dd1ac86e8854d4fb9fe5fbafaec2b98",
        resource_type: "App Connector",
        resource_url: "https://www.hydroshare.org/resource/2dd1ac86e8854d4fb9fe5fbafaec2b98/",
        thumbnail_url: "https://ciroh.ua.edu/wp-content/uploads/2022/08/CIROHLogo_200x200.png",
        title: "CIROH-2i2c JupyterHub",
    },
]

