# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'CD: Deploy build artifact to composite target'

on:
  repository_dispatch:
    types: [build-completed]
  workflow_dispatch:  # For manual triggering if needed

env:
  PROD_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}
  PROD_PATH: .
  STAGING_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}
  STAGING_PATH: staging/
  STAGING_MAIN_FOLDER: main/ # Future-proofing for PR staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-outputs.outputs.environment }}
      version: ${{ steps.set-outputs.outputs.version }}
      
    name: ${{ github.event.client_payload.env }} - Deploy ${{ github.event.client_payload.short_hash }} from ${{ github.event.client_payload.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure detached HEAD state to avoid conflicts with the main branch
          ref: refs/heads/main

      # Get environment and version from dispatch payload
      - name: Echo environment from dispatch
        run: |
          echo "DEPLOY_ENV=${{ github.event.client_payload.env }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

          echo "Deploying commit ${{ github.event.client_payload.commit_hash }}"
          echo "Commit message: ${{ github.event.client_payload.commit_message }}"
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "Deploying version: ${{ github.event.client_payload.version }}"
          echo "Environment: ${{ github.event.client_payload.env }}"
          
      # https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download a Build Artifact
        uses: dawidd6/action-download-artifact@v2.26.1
        with:
          workflow: ci_pipeline.yml
          name: build-${{ env.DEPLOY_ENV }}
          path: ./build/

      - name: Set deployment target
        id: set-outputs
        run: |
          if [[ "$DEPLOY_ENV" == "production" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "TARGET_REPO=$PROD_REPO" >> $GITHUB_ENV
            echo "TARGET_PATH=$PROD_PATH" >> $GITHUB_ENV
            echo "Deploying to $TARGET_REPO as PRODUCTION at path $TARGET_PATH"
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "TARGET_REPO=${{ env.STAGING_REPO }}" >> $GITHUB_ENV
            echo "TARGET_PATH=${{ env.STAGING_PATH }}${{ env.STAGING_MAIN_FOLDER }}'" >> GITHUB_ENV
            echo "Deploying to $STAGING_REPO as STAGING at path $STAGING_PATH$STAGING_MAIN_FOLDER"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Deployment preview
        run: |
          echo "Deploying to $TARGET_REPO as $ENVIRONMENT at path $TARGET_PATH"

      - name: Deploy to composite repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "./build/"
          ssh-key: ${{ secrets.SSH_DEPLOY_HUB_SUBDOMAIN }}
          repository-name: ${{ env.TARGET_REPO }}
          target-folder: ${{ env.TARGET_PATH }}
          clean: $ENVIRONMENT == 'production' # Set to false if deploying to a composite repository's root!

      - name: Post-deployment notification
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "production" ]]; then
            echo "### Production build artifact uploaded! 🚀" >> $GITHUB_STEP_SUMMARY
          else
            echo "Staging build artifact uploaded! 🚀"
            echo "To deploy to production, manually trigger the 'CI: Trigger staging deployment from main' workflow." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ needs.deploy.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deploy Target**: $TARGET_REPO -> $TARGET_PATH" >> $GITHUB_STEP_SUMMARY
          echo "- **URL (once live)**: https://hub.ciroh.org/$BASE_URL" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Deployment to GitHub Pages will be completed by the composite target repository, $TARGET_REPO." >> $GITHUB_STEP_SUMMARY