# Triggers a CI/CD deployment from the main branch to staging.

name: 'CI: Trigger staging deployment from main'

on:
  push:
    branches:
    - main
    - test-deploy
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Send repository dispatch'
      uses: peter-evans/repository-dispatch@v4
      with:
        event-type: create-build
        client-payload: '{"deploy_env": "staging", "base_url": "/staging/main/"}'
