# Triggers a CI/CD deployment from the main branch to production.

name: 'CI: Trigger production deployment from main'

on:
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Send repository dispatch'
      uses: peter-evans/repository-dispatch@v4
      with:
        event-type: create-build
        client-payload: '{"deploy_env": "production", "base_url": "/"}'
